### ISSUE TITLE
模型测试不出

### ISSUE THREAD

**Issue by cjl506** [DeniJsonC/PPformer#1]
我想引用你的算法作为对比试验，你的模型测试不出的你的结果呢，期待你的回复
![image](https://github.com/DeniJsonC/PPformer/assets/83258906/943915e6-5c9f-493c-a974-1a3d9e53cfba)

**Comment by DeniJsonC** [comment]
> 我想引用你的算法作为对比试验，你的模型测试不出的你的结果呢，期待你的回复 ![image](https://private-user-images.githubusercontent.com/83258906/341358007-943915e6-5c9f-493c-a974-1a3d9e53cfba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4ODQzNzYsIm5iZiI6MTcxODg4NDA3NiwicGF0aCI6Ii84MzI1ODkwNi8zNDEzNTgwMDctOTQzOTE1ZTYtNWM5Zi00OTNjLWE5NzQtMWEzZDllNTNjZmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDExNDc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZjBkODI3YzcwYzk4YzJlN2JhNGM3MjhjYzBiMWY4YjNkMGJjNTVkOGI4YTE5NGZhOTYwNzgwMzEyZDFjNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RffYDvd1af472jAfx98mpFCNkrXLs8bKhvqq4B7pV1w)

你好  我测试出来是正确的，请问你用visual文件夹里提供的图片测试出来也是这样吗

**Comment by cjl506** [comment]
visual文件夹里面的提供图像是亮图啊，我用的是lol数据集的eval15/low中的图像啊，那您把你的测试结果发给我一下可以吗，我用来贴在我的论文里面

**Comment by DeniJsonC** [comment]
> visual文件夹里面的提供图像是亮图啊，我用的是lol数据集的eval15/low中的图像啊，那您把你的测试结果发给我一下可以吗，我用来贴在我的论文里面
你好，这是具体结果。 visual文件夹就是模型以lol数据集中low文件夹作为输入得到的增强后的结果。

<img width="332" alt="截屏2024-06-20 20 14 34" src="https://github.com/DeniJsonC/PPformer/assets/38310908/023758e3-b85a-440d-88d2-f0a6a32b41a9">

**Comment by cjl506** [comment]
谢谢，可否把您的测试的图像结果分享一下呢，论文需要对比图像视觉结果，万分感谢

**Comment by DeniJsonC** [comment]
> 谢谢，可否把您的测试的图像结果分享一下呢，论文需要对比图像视觉结果，万分感谢

感谢你对我们工作的关注。你需要什么数据集的可视化图像呢，若是lol的，visual文件夹里面就是lol数据集的增强结果。其它数据集的可以留下邮箱，发你邮箱。另外我想知道你的你提供的测试结果是怎么得出的呢？正常的话加载lol权重，运行demo.py文件将low-light图像生成增强后图像，再运行evaluation.py文件将生成的图像和eval15/high文件夹下的图像计算PSNR SSIM LPIPS。

**Comment by cjl506** [comment]
我的文件太大了，我的qq是1141643870，您能加我一下吗，我需要LOL，lol-v2，Nikon，Huawei数据集的结果，我可以把数据集发给您，我想可能是这边的问题，很遗憾有这样的情况发生，非常感谢您
![image](https://github.com/DeniJsonC/PPformer/assets/83258906/9c954f3d-b17a-425b-9109-ead87dc9d053)

**Comment by xuehaohewangyu** [comment]
> 我想你的算法运行情况，你的模型开发情况，你的工作成果 ![图像](https://private-user-images.githubusercontent.com/83258906/341358007-943915e6-5c9f-493c-a974-1a3d9e53cfba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjY2MzgsIm5iZiI6MTcyMDE2NjMzOCwicGF0aCI6Ii84MzI1ODkwNi8zNDEzNTgwMDctOTQzOTE1ZTYtNWM5Zi00OTNjLWE5NzQtMWEzZDllNTNjZmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA3NTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMjk3NTRlZTA1YzU0MTk2NTkzNWRlODEwMWYzODUyYmEyNGY0ZWNkZTNiZmNjZmUzMmZjZjQxMzFkNWE4NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DJQgr8-YyQdT2oxrOJBED2aNJPnLMY6FpymFIPIklUY)

大佬你好，我运行evaluation.py出现报错  你怎么运行的  能给出命令示例吗 如：python evaluation.py -dirA D:/llfw--reproduce/kongjianyu/PPformer-main-2024/loltest -dirB D:/llfw--reproduce/kongjianyu/PPformer-main-2024/lolv1/lolhigh -type png --use_gpu True

**Comment by xuehaohewangyu** [comment]
> > 我想你的算法运行情况，你的模型开发情况，你的工作成果![图像](https://private-user-images.githubusercontent.com/83258906/341358007-943915e6-5c9f-493c-a974-1a3d9e53cfba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjY2MzgsIm5iZiI6MTcyMDE2NjMzOCwicGF0aCI6Ii84MzI1ODkwNi8zNDEzNTgwMDctOTQzOTE1ZTYtNWM5Zi00OTNjLWE5NzQtMWEzZDllNTNjZmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA3NTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMjk3NTRlZTA1YzU0MTk2NTkzNWRlODEwMWYzODUyYmEyNGY0ZWNkZTNiZmNjZmUzMmZjZjQxMzFkNWE4NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DJQgr8-YyQdT2oxrOJBED2aNJPnLMY6FpymFIPIklUY)
> 
> 大佬你好，我运行evaluation.py出现报错 你能给出命令示例吗 如：python evaluation.py -dirA D:/llfw--reproduce/kongjianyu/PPformer-main-2024/loltest -dirB D:/llfw--reproduce/kongjianyu/PPformer-main-2024/lolv1/lolhigh -type png --use_gpu True

![image](https://github.com/DeniJsonC/PPformer/assets/118803631/f1d5510a-59eb-48b6-b2ae-48443bdd0f6c)

**Comment by DeniJsonC** [comment]
> > > 我想你的算法运行情况，你的模型开发情况，你的工作成果![图像](https://private-user-images.githubusercontent.com/83258906/341358007-943915e6-5c9f-493c-a974-1a3d9e53cfba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjY2MzgsIm5iZiI6MTcyMDE2NjMzOCwicGF0aCI6Ii84MzI1ODkwNi8zNDEzNTgwMDctOTQzOTE1ZTYtNWM5Zi00OTNjLWE5NzQtMWEzZDllNTNjZmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA3NTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMjk3NTRlZTA1YzU0MTk2NTkzNWRlODEwMWYzODUyYmEyNGY0ZWNkZTNiZmNjZmUzMmZjZjQxMzFkNWE4NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DJQgr8-YyQdT2oxrOJBED2aNJPnLMY6FpymFIPIklUY)
> > 
> > 
> > 大佬你好，我运行evaluation.py出现报错 你能给出命令示例吗 如：python evaluation.py -dirA D:/llfw--reproduce/kongjianyu/PPformer-main-2024/loltest -dirB D:/llfw--reproduce/kongjianyu/PPformer-main-2024/lolv1/lolhigh -type png --use_gpu True
> 
> ![image](https://private-user-images.githubusercontent.com/118803631/346051804-f1d5510a-59eb-48b6-b2ae-48443bdd0f6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjgwMjMsIm5iZiI6MTcyMDE2NzcyMywicGF0aCI6Ii8xMTg4MDM2MzEvMzQ2MDUxODA0LWYxZDU1MTBhLTU5ZWItNDhiNi1iMmFlLTQ4NDQzYmRkMGY2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQwODIyMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGE3YTllZmI3MDAxYzllMTE1OTFhMjE1YmZhY2UwODg2ODUxMWE0ZmQ3YTZlMzgxMmY4YWVlYzY1YmEwZDE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1W8B3fOUzdSEGh2skOAO-JSEy_FuC-LymCP2CCe4cH0)

你好，这是scikit-image版本原因。    运行命令： pip install scikit-image==0.19.2

**Comment by xuehaohewangyu** [comment]
![image](https://github.com/DeniJsonC/PPformer/assets/118803631/e346421e-1c80-470a-8d24-e47291daa4e8)
下载了scikit-image==0.19.2出现这个错误
